spring.application.name=moneywallet

# === DATABASE CONFIG ===
spring.datasource.url=jdbc:mysql://localhost:3306/moneywallet
spring.datasource.username=root
spring.datasource.password=BlairVullu@2001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === JWT CONFIG ===
application.security.jwt.secret=40QyyYZ9IleQ8Obh9FSYpxFfeDcxJpK1dMuKk8zH370=
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=604800000