# Service name
spring.application.name=auth-service
server.port=8081

#Wallet Service URL for the AuthServiceClient
wallet.service.url=http://localhost:8084

# Spring Security OAuth2 Resource Server JWT configuration
spring.security.oauth2.resourceserver.jwt.secret=Z+lPWf8G6kX94v6MoDSyAZOjW5lg6Xe8I8d0ayhvlMg=

# JWT
jwt.secret=Z+lPWf8G6kX94v6MoDSyAZOjW5lg6Xe8I8d0ayhvlMg=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emiseduvod@gmail.com
spring.mail.password=thwm wrmv oaql sogu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# === SPRINGDOC / SWAGGER ===
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs

# === DATABASE CONFIG (PostgreSQL) ===
#spring.datasource.url=jdbc:postgresql://localhost:5433/AuthDB
#spring.datasource.username=localhost
#spring.datasource.password=123456789
#spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Kafka producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=5

# Default topic for KafkaTemplate
spring.kafka.template.default-topic=user-registered.v1

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.springframework.security=DEBUG
logging.level.com.cashbox.authservice=DEBUG
